stages:
  - test
  - setup env
  - build
  - deploy

variables:
  WEBSERVER_FOLDER_NAME: vus_portal

.only_staging:
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: always
      - when: never

.only_production:
    rules:
      - if: $CI_COMMIT_BRANCH == 'production'
        when: always
      - when: never


####################################################################################################
include:
  - component: $CICD_COMPONENTS_PROJECT/lint_eslint@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: test

  - component: $CICD_COMPONENTS_PROJECT/build_vite@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: build
    rules:
      - if: $CI_COMMIT_REF_PROTECTED == false
        when: always
      - when: never

  - component: $CICD_COMPONENTS_PROJECT/build_vite@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: build
      input_env_file: deploy.env
      output_env_file: production.env
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: always
      - when: never


  - component: $CICD_COMPONENTS_PROJECT/build_vite@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: build
    rules:
      - if: $CI_COMMIT_BRANCH == 'production'
        when: always
      - when: never
  
  - component: $CICD_COMPONENTS_PROJECT/deploy_to_static_webserver@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: deploy
      folder_name: $WEBSERVER_FOLDER_NAME
      environment: staging
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: always
      - when: never


  - component: $CICD_COMPONENTS_PROJECT/deploy_to_static_webserver@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: deploy
      folder_name: $WEBSERVER_FOLDER_NAME
      environment: production
    rules:
      - if: $CI_COMMIT_BRANCH == 'production'
        when: always
      - when: never
