stages:
  - test
  - setup env
  - build
  - deploy

variables:
  WEBSERVER_FOLDER_NAME: vus_portal

.only staging:
    rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        when: always
      - when: never

.only production:
    rules:
      - if: $CI_COMMIT_BRANCH == 'production'
        when: always
      - when: never


####################################################################################################
include:
  - component: $CICD_COMPONENTS_PROJECT/test_eslint@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: test

  - component: $CICD_COMPONENTS_PROJECT/build_file_for_environment@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: setup env
      environment: staging
      inputs:
        input_file: deploy.env
        output_file: production.env
      rules:
        - !reference [.only staging, rules]

  - component: $CICD_COMPONENTS_PROJECT/build_file_for_environment@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: setup env
      environment: production
      inputs:
        input_file: deploy.env
        output_file: production.env
      rules:
        - !reference [.only production, rules]

  - component: $CICD_COMPONENTS_PROJECT/build_vite@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: build
      environment: staging
    rules:
      - !reference [.only staging, rules]

  - component: $CICD_COMPONENTS_PROJECT/build_vite@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: build
      environment: production
    rules:
      - !reference [.only production, rules]
  
  - component: $CICD_COMPONENTS_PROJECT/deploy_to_static_webserver@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: deploy
      folder_name: $WEBSERVER_FOLDER_NAME
      environment: staging
    rules:
      - !reference [.only staging, rules]

  - component: $CICD_COMPONENTS_PROJECT/deploy_to_static_webserver@$CICD_COMPONENTS_COMMIT_REF
    inputs:
      stage: deploy
      folder_name: $WEBSERVER_FOLDER_NAME
      environment: production
    rules:
      - !reference [.only production, rules]
